'use strict';
const $ = (q) => document.querySelector(q);
const $$ = (q) => [...document.querySelectorAll(q)];
const world = $('#world'), workspace = $('#workspace');
const reducedQuery = window.matchMedia('(prefers-reduced-motion: reduce)');
let reduced = reducedQuery.matches, view = 'room', travel = 0, targetTravel = 0;
let lookX = 0, lookY = 0, targetLookX = 0, targetLookY = 0;
let transitionToken = 0, tourToken = 0, touring = false, toastTimer, saveTimer;
let lastFrame = performance.now(), animationFrame = 0;
let storageKey = 'estate-scriptorium-demo-v1';
const initialDocs = [
 {id:'chapter-1', name:'Chapter 1', subtitle:'The threshold', title:'The Unfinished City', text:'The city rose from the water like a question, its upper terraces lost in morning haze. Mara paused at the threshold, feeling the hum of a thousand unseen lives. Beyond the arch, the causeways lifted toward the spire, yet the lower districts remained in shadow, unfinished, as if the city were still deciding what it wanted to be.\n\nJoren glanced at her. “It’s not abandoned,” he said. “It’s in between. A city is never finished, only deferred.”\n\nMara studied the carvings on the doorway — tools, waves, and open hands. Someone had imagined a different tomorrow here.\n\nInside, the air changed. Cooler, dusted with the scent of stone and salt. The unfinished city breathed around her, patient, waiting for the people who would give it a new shape.', suggestion:'She stepped forward, not as a visitor, but as a witness.', disposition:'pending'},
 {id:'chapter-2', name:'Chapter 2', subtitle:'The room beyond', title:'The Room Beyond', text:'The room was already occupied, though no one seemed to have arrived. A woman was turning a sheet of glass toward the light. Two people at the long table were discussing a sentence as if it were a small bridge they were about to cross.\n\nMara found a desk beside the opening. Someone had left enough space for her to begin.\n\nShe sat down. For the first time that morning, she knew what she wanted to make.', suggestion:'Beyond the table, a doorway opened onto the sound of someone trying again.', disposition:'pending'},
 {id:'scene-notes', name:'Scene notes', subtitle:'Images, rhythm, intention', title:'A Doorway into the Story', text:'The threshold should feel like an invitation.\n\nMara is curious, but not yet certain that she belongs. Joren gives her room to decide.\n\nVisual notes\nWarm light across the floor. A glimpse of work still in progress. Materials that show the hands that shaped them.\n\nSound notes\nA low conversation. The turn of a page. A pause long enough to hear the room.', suggestion:'Keep the first glimpse incomplete: the room should promise more than the doorway reveals.', disposition:'pending'}
];
let docs = structuredClone(initialDocs), activeId = 'chapter-1', saveAvailable = true, savedAt = null;
try { const saved=JSON.parse(localStorage.getItem(storageKey)||'null'); if(saved?.version===1&&Array.isArray(saved.docs)){ docs=initialDocs.map(d=>{const s=saved.docs.find(x=>x.id===d.id);return s&&typeof s.text==='string'&&typeof s.suggestion==='string'?{...d,text:s.text,suggestion:s.suggestion,disposition:['pending','accepted','dismissed'].includes(s.disposition)?s.disposition:'pending'}:{...d}}); savedAt=saved.savedAt; }} catch {saveAvailable=false;}
const currentDoc=()=>docs.find(d=>d.id===activeId);
const esc=(s)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
workspace.innerHTML=`
<header class="desk-header"><button class="return-button" id="returnToRoom">← <span>Return to room</span></button><div class="desk-identity"><span class="emblem">✳</span><span>Your writing desk<small>The Scriptorium</small></span></div><div class="desk-tools"><button class="quiet-button" id="focusButton" aria-pressed="false">Focus</button><button class="quiet-button" id="pageTourButton">▷ Tour</button><button class="quiet-button" id="downloadButton" title="Download this document">Export ↓</button></div></header>
<nav class="mobile-tabs" aria-label="Writing panes"><button data-pane="binder">Binder</button><button data-pane="page" aria-current="page">Page</button><button data-pane="studio">Studio</button></nav>
<div class="desk-layout" data-pane="page">
<aside class="binder-pane" aria-label="Binder"><div class="pane-title">Binder <span>01</span></div><div class="binder-section-label">MANUSCRIPT</div><div id="documentList"></div><div class="binder-section-label resources-label">YOUR MATERIALS</div><button class="resource-button" data-resource="sources"><span>▤</span> Sources <small>2</small></button><button class="resource-button" data-resource="evidence"><span>⌁</span> Evidence <small>—</small></button><button class="resource-button" data-resource="assets"><span>▧</span> Scene studies <small>2</small></button><div class="binder-bottom"><span class="private-symbol">◇</span><div>Private writing<small>Shared room, your own draft</small></div></div></aside>
<section class="page-pane" aria-label="Manuscript"><div class="page-toolbar"><span id="chapterLabel">Chapter 1 / The threshold</span><span class="page-tag">DRAFT</span></div><article class="manuscript"><div class="manuscript-eyebrow">THE UNFINISHED CITY</div><h2 id="documentTitle"></h2><div id="editor" contenteditable="true" role="textbox" aria-label="Manuscript text" aria-multiline="true" spellcheck="true"></div><section id="suggestionInline" class="inline-suggestion" aria-label="Proposed addition"><div class="suggestion-kicker">PROPOSED ADDITION</div><p id="inlineSuggestionText"></p><div class="suggestion-actions"><button id="acceptSuggestion" class="amber-button">Accept</button><button id="reviseSuggestion" class="outline-button">Revise</button><button id="dismissSuggestion" class="text-button">Dismiss</button></div><div id="reviseBox" hidden><label for="revisedText">Make it your own</label><textarea id="revisedText" rows="3"></textarea><button id="applyRevision" class="amber-button">Use this revision</button><button id="cancelRevision" class="text-button">Cancel</button></div></section><div class="end-mark">✳</div></article></section>
<aside class="studio-pane" aria-label="Generated studies and suggestions"><div class="pane-title">Studio <span>02</span></div><div class="studio-eyebrow">A SCENE TO THINK WITH</div><button id="heroStudyButton" class="study-image-button" aria-label="Enlarge the interior scene study"><img id="heroStudy" src="assets/scene-study.png" alt="A proposed visual study of an inhabited, warmly lit room"><span>View study ↗</span></button><div class="study-thumbnails"><button data-study="scene-study.png" class="selected" aria-label="Select intimate room study" aria-pressed="true"><img src="assets/scene-study.png" alt="Intimate room"><span>The room</span></button><button data-study="room.png" aria-label="Select doorway study" aria-pressed="false"><img src="assets/room.png" alt="View through the doorway"><span>The arrival</span></button></div><div class="result-card"><span class="result-label">A POSSIBLE ENDING</span><p id="studioSuggestionText"></p><div class="result-basis">A prepared suggestion for this concept.</div><button id="stageSuggestion" class="outline-button full-width">Review on the page ↗</button></div><div class="studio-note"><span>✧</span><p>Keep what belongs.<br>Change what could be better.</p></div><div class="demo-note">Concept studies and prepared suggestions.<br>No live agent is connected.</div></aside>
</div><footer class="desk-rail"><span id="wordCount"></span><span id="saveState">Saved on this device</span><span class="rail-spacer"></span><span class="rail-privacy">◇ Private draft</span><button id="resetButton">Reset demo</button></footer>
<dialog id="resourceDialog"><div class="modal-heading"><h3 id="modalTitle"></h3><button id="closeDialog" aria-label="Close dialog">×</button></div><div id="modalBody"></div></dialog>`;
function renderDocs(){ $('#documentList').innerHTML=docs.map(d=>`<button class="document-button ${d.id===activeId?'selected':''}" data-doc="${d.id}" ${d.id===activeId?'aria-current="page"':''}><span class="doc-icon">▤</span><span>${esc(d.name)}<small>${esc(d.subtitle)}</small></span></button>`).join(''); $$('[data-doc]').forEach(b=>b.onclick=()=>{stopTour();persist();activeId=b.dataset.doc;renderDocument();setPane('page');}); }
function renderDocument(){const d=currentDoc();$('#documentTitle').textContent=d.title;$('#chapterLabel').textContent=d.name+' / '+d.subtitle;$('#editor').textContent=d.text;$('#inlineSuggestionText').textContent=d.suggestion;$('#studioSuggestionText').textContent=d.suggestion;$('#suggestionInline').hidden=d.disposition!=='pending';$('#reviseBox').hidden=true;$('#stageSuggestion').disabled=d.disposition==='accepted';$('#stageSuggestion').textContent=d.disposition==='accepted'?'Added to your manuscript':'Review on the page ↗';renderDocs();updateWordCount();updateSaveState();if(window.refreshPractice)refreshPractice();}
function updateWordCount(){const n=currentDoc().text.trim().split(/\s+/).filter(Boolean).length;$('#wordCount').textContent=n.toLocaleString()+' words';}
function updateSaveState(){ $('#saveState').textContent=saveAvailable?(savedAt?'Saved on this device':'Demo draft · changes save here'):'Not saved · export to keep your draft'; }
function persist(){clearTimeout(saveTimer);try{savedAt=new Date().toISOString();localStorage.setItem(storageKey,JSON.stringify({version:1,docs,savedAt}));saveAvailable=true;}catch{saveAvailable=false;}updateSaveState();}
$('#editor').addEventListener('input',()=>{stopTour();currentDoc().text=$('#editor').innerText;$('#saveState').textContent='Saving on this device…';updateWordCount();clearTimeout(saveTimer);saveTimer=setTimeout(persist,400);});
$('#editor').addEventListener('paste',event=>{event.preventDefault();const text=event.clipboardData.getData('text/plain');const sel=window.getSelection();if(!sel.rangeCount)return;const range=sel.getRangeAt(0);if(!$('#editor').contains(range.commonAncestorContainer))return;range.deleteContents();const node=document.createTextNode(text);range.insertNode(node);range.setStartAfter(node);range.collapse(true);sel.removeAllRanges();sel.addRange(range);$('#editor').dispatchEvent(new Event('input',{bubbles:true}));});
function accept(text){stopTour();const d=currentDoc();if(d.disposition==='accepted')return;d.text=d.text.trimEnd()+'\n\n'+text;d.suggestion=text;d.disposition='accepted';persist();renderDocument();toast('Added to your manuscript.');}
$('#acceptSuggestion').onclick=()=>accept(currentDoc().suggestion);
$('#reviseSuggestion').onclick=()=>{stopTour();$('#reviseBox').hidden=false;$('#revisedText').value=currentDoc().suggestion;$('#revisedText').focus();};
$('#applyRevision').onclick=()=>{const t=$('#revisedText').value.trim();if(t)accept(t);};
$('#cancelRevision').onclick=()=>$('#reviseBox').hidden=true;
$('#dismissSuggestion').onclick=()=>{stopTour();currentDoc().disposition='dismissed';persist();renderDocument();toast('Suggestion set aside.');};
$('#stageSuggestion').onclick=()=>{stopTour();currentDoc().disposition='pending';persist();renderDocument();setPane('page');$('#suggestionInline').scrollIntoView({behavior:reduced?'instant':'smooth',block:'center'});};
function setPane(p){$('.desk-layout').dataset.pane=p;$$('[data-pane]').filter(b=>b.tagName==='BUTTON').forEach(b=>{if(b.dataset.pane===p)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
$$('.mobile-tabs button').forEach(b=>b.onclick=()=>{stopTour();setPane(b.dataset.pane);});
$('#focusButton').onclick=()=>{stopTour();const active=workspace.classList.toggle('focus-mode');$('#focusButton').setAttribute('aria-pressed',String(active));$('#focusButton').textContent=active?'Show panes':'Focus';};
$('#downloadButton').onclick=()=>{stopTour();persist();const d=currentDoc();const url=URL.createObjectURL(new Blob(['# '+d.title+'\n\n'+d.text+'\n'],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=d.id+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Your manuscript has been exported.');};
function openModal(title,html){stopTour();$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#resourceDialog').showModal();}
$('#closeDialog').onclick=()=>$('#resourceDialog').close();
$('#resourceDialog').addEventListener('click',e=>{if(e.target===$('#resourceDialog'))$('#resourceDialog').close();});
$('#heroStudyButton').onclick=()=>openModal('A scene study',`<img class="large-study" src="${$('#heroStudy').getAttribute('src')}" alt="Selected architectural scene study"><p class="modal-note">Generated concept artwork. A visual possibility for the story.</p>`);
$$('[data-study]').forEach(b=>b.onclick=()=>{stopTour();$('#heroStudy').src='assets/'+b.dataset.study;$$('[data-study]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});});
$$('[data-resource]').forEach(b=>b.onclick=()=>{const type=b.dataset.resource;if(roomId==='laboratory'){openResearchResource(type);return;}if(type==='sources')openModal('Sources for this scene','<div class="source-item"><span>01</span><div><h4>A city still becoming</h4><p>Story note: the setting should feel occupied and unfinished. Its inhabitants continue to shape it.</p></div></div><div class="source-item"><span>02</span><div><h4>The gesture of invitation</h4><p>Scene note: Mara is offered a place to work, with enough room to decide for herself.</p></div></div><p class="modal-note">Fictional reference notes prepared for this demonstration.</p>');else if(type==='evidence')openModal('Evidence','<p class="empty-message">This fictional scene has no research evidence attached.</p><p class="modal-note">In a research project, this space would hold experiments, figures and supporting records.</p>');else openModal('Scene studies','<div class="asset-grid"><img src="assets/scene-study.png" alt="Intimate room study"><img src="assets/room.png" alt="Doorway study"></div><p class="modal-note">Two visual interpretations of the same imagined place.</p>');});
$('#resetButton').onclick=()=>{openModal('Reset this demonstration?','<p>Your edits to these sample documents will be replaced with the original demo text. Export anything you want to keep first.</p><div class="modal-actions"><button class="outline-button" id="cancelReset">Keep my writing</button><button class="amber-button" id="confirmReset">Reset sample documents</button></div>');$('#cancelReset').onclick=()=>$('#resourceDialog').close();$('#confirmReset').onclick=()=>{docs=structuredClone(roomId==='laboratory'?researchDocs:initialDocs);activeId='chapter-1';persist();renderDocument();$('#resourceDialog').close();toast('Demo documents restored.');};};
function toast(t){clearTimeout(toastTimer);$('#toast').textContent=t;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,3200);}
function updateNavigation(){document.body.dataset.view=view;$$('[data-go]').forEach(b=>{if(b.dataset.go===view)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});$('#deskPrompt').hidden=view!=='desk'||touring;$('#backButton').hidden=view!=='desk';$('#navigationHint').hidden=view==='desk';$('#deskHotspot').disabled=view!=='room';$('#deskHotspot').setAttribute('tabindex',view==='room'?'0':'-1');$('#sceneDescription').textContent=currentRoom().description;$('#roomDoors').hidden=view!=='room'||touring;}
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function go(next,fromTour=false){if(!['room','desk','page'].includes(next)||document.documentElement.classList.contains('gated')||document.body.classList.contains('changing-room'))return;if(!fromTour)stopTour();if(next===view)return;const token=++transitionToken;
 if(next==='page'){
   if(view==='room'){view='desk';targetTravel=1;targetLookX=0;targetLookY=0;updateNavigation();wake();await delay(reduced?0:2600);if(token!==transitionToken||(fromTour&&!touring))return;}
   view='page';targetTravel=1;persist();prepareSurface();workspace.hidden=false;workspace.inert=false;updateNavigation();await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);if(token!==transitionToken)return;workspace.classList.add('visible');$('#worldHeader').inert=true;$('#worldFooter').inert=true;world.inert=true;setPane('page');if(!fromTour)$('#returnToRoom').focus({preventScroll:true});
 }else{
   if(view==='page'){stopAnimatic();persist();$('#resourceDialog').close();workspace.classList.remove('visible');workspace.inert=true;$('#worldHeader').inert=false;$('#worldFooter').inert=false;world.inert=false;view=next;updateNavigation();await delay(reduced?0:650);if(token!==transitionToken)return;workspace.hidden=true;}
   view=next;targetTravel=next==='desk'?1:0;targetLookX=0;targetLookY=0;updateNavigation();wake();if(!fromTour)(next==='room'?$('#deskHotspot'):$('#openPageButton')).focus({preventScroll:true});
 }
}
$('#deskHotspot').onclick=()=>go('desk');$('#openPageButton').onclick=()=>go('page');$('#backButton').onclick=()=>go('room');$('#returnToRoom').onclick=()=>go('room');$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function draw(now){const dt=Math.min((now-lastFrame)/1000,.05);lastFrame=now;const ease=reduced?1:1-Math.exp(-dt*2.2);travel+=(targetTravel-travel)*ease;lookX+=(targetLookX-lookX)*(reduced?1:.09);lookY+=(targetLookY-lookY)*(reduced?1:.09);const w=innerWidth,h=innerHeight,r=currentRoom(),aspect=r.aspect,cw=Math.max(w,h*aspect),ch=cw/aspect;const s=1.045+travel*r.zoom;const restShift=Math.max(-(cw-w)/2,Math.min((cw-w)/2,-(r.focus[0]-.5)*cw));const rawX=lookX*(1-travel*.6)+restShift*(1-travel)-(r.focus[0]-.5)*cw*s*travel;const rawY=-(r.focus[1]-.5)*ch*travel*s+lookY*(1-travel*.6);const x=Math.max(-(cw*s-w)/2,Math.min((cw*s-w)/2,rawX));const y=Math.max(-(ch*s-h)/2,Math.min((ch*s-h)/2,rawY));$('#camera').style.width=cw+'px';$('#camera').style.height=ch+'px';$('#camera').style.transform=`translate(-50%,-50%) translate3d(${x}px,${y}px,0) scale(${s})`;
 const blend=r.seat?Math.max(0,Math.min(1,(travel-.55)/.4)):0;$('#seatedCamera').style.opacity=blend;$('#seatedCamera').style.transform=`scale(${1.1-.1*blend}) translate3d(${lookX*.2}px,${lookY*.2}px,0)`;
 const hx=w/2+(r.focus[0]-.5)*cw*s+x,hy=h/2+(r.focus[1]-.5)*ch*s+y;$('#deskHotspot').style.left=Math.max(95,Math.min(w-95,hx))+'px';$('#deskHotspot').style.top=Math.max(150,Math.min(h-180,hy))+'px';
 if(Math.abs(targetTravel-travel)>.0002||Math.abs(targetLookX-lookX)>.1||Math.abs(targetLookY-lookY)>.1){animationFrame=requestAnimationFrame(draw);}else{animationFrame=0;}
}
function wake(){if(!animationFrame){lastFrame=performance.now();animationFrame=requestAnimationFrame(draw);}}
window.addEventListener('resize',wake);$('#roomImage').addEventListener('load',wake);$('#roomImage').addEventListener('error',()=>{toast('The room image could not load. You can still open the Page view.');});
let drag=null,moved=false,lastWheel=0;
world.addEventListener('pointerdown',e=>{if(e.target.closest('button,a')||document.body.classList.contains('changing-room'))return;stopTour();drag={x:e.clientX,y:e.clientY,lx:targetLookX,ly:targetLookY};moved=false;world.setPointerCapture(e.pointerId);world.classList.add('looking');});
world.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;moved||=Math.abs(dx)+Math.abs(dy)>4;targetLookX=Math.max(-innerWidth*.095,Math.min(innerWidth*.095,drag.lx+dx*.35));targetLookY=Math.max(-innerHeight*.04,Math.min(innerHeight*.04,drag.ly+dy*.2));wake();});
function endDrag(){drag=null;world.classList.remove('looking');}world.addEventListener('pointerup',endDrag);world.addEventListener('pointercancel',endDrag);
world.addEventListener('wheel',e=>{if(view==='page')return;e.preventDefault();const now=performance.now();if(now-lastWheel<2200||Math.abs(e.deltaY)<18)return;lastWheel=now;if(e.deltaY>0)go(view==='room'?'desk':'page');else go('room');},{passive:false});
document.addEventListener('keydown',e=>{if(document.documentElement.classList.contains('gated')||document.body.classList.contains('changing-room')||$('#resourceDialog').open||$('#placesDialog').open)return;if(e.key==='Escape'){e.preventDefault();stopTour();if(view==='page')go('desk');else go('room');}else if(e.target.closest('input,textarea,[contenteditable=true]'))return;else if(view!=='page'&&['ArrowUp','w','W'].includes(e.key)){e.preventDefault();go(view==='room'?'desk':'page');}else if(view!=='page'&&['ArrowDown','s','S'].includes(e.key)){e.preventDefault();go('room');}else if(view!=='page'&&['ArrowLeft','a','A','ArrowRight','d','D'].includes(e.key)){e.preventDefault();stopTour();targetLookX=Math.max(-innerWidth*.095,Math.min(innerWidth*.095,targetLookX+(['ArrowLeft','a','A'].includes(e.key)?45:-45)));wake();}});
function setReduced(value){reduced=value;document.documentElement.classList.toggle('no-motion',reduced);$('#motionButton').setAttribute('aria-pressed',String(reduced));$('#motionButton').setAttribute('aria-label',reduced?'Enable camera motion':'Reduce motion');wake();}
$('#motionButton').onclick=()=>{setReduced(!reduced);toast(reduced?'Reduced motion enabled.':'Camera motion enabled.');};reducedQuery.addEventListener('change',e=>setReduced(e.matches));
$('#fullscreenButton').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Fullscreen is not available in this browser.');}};
document.addEventListener('fullscreenchange',()=>$('#fullscreenButton').setAttribute('aria-label',document.fullscreenElement?'Exit fullscreen':'Enter fullscreen'));
function stopTour(){if(!touring)return;touring=false;tourToken++;$('#tourCaption').hidden=true;$('#tourButton').textContent='▷ Guided tour';$('#pageTourButton').textContent='▷ Tour';updateNavigation();}
async function startTour(){
 if(touring){stopTour();return;}
 if(document.body.classList.contains('changing-room'))return;
 touring=true;const token=++tourToken;
 $('#tourButton').textContent='■ Stop tour';$('#pageTourButton').textContent='■ Stop tour';
 const caption=t=>{if(token!==tourToken)return;$('#tourCaption').textContent=t;$('#tourCaption').hidden=false;};
 const wait=async ms=>{await delay(ms);return token===tourToken;};
 const route=[
 ['scriptorium','Begin with a room, then a desk, then a page of your own.'],
 ['laboratory','Through the next doorway: write beside the experiment.'],
 ['makers','Carry an idea into the studio. Give it an image and a rhythm.'],
 ['marketplace','The evening market: find a study to bring back to your bench.']
 ];
 for(const [place,line] of route){
   await enterRoom(place,true);if(token!==tourToken)return;
   caption(line);targetLookX=18;wake();if(!await wait(2800))return;
   await go('desk',true);if(token!==tourToken)return;if(!await wait(2500))return;
   await go('page',true);if(token!==tourToken)return;
   caption(place==='scriptorium'?'Your manuscript fills the screen. Your writing stays yours.':place==='laboratory'?'Compare the sample curves and write your own interpretation.':place==='makers'?'Select frames, change their order, and preview a short animatic.':'Browse the studies. Bring one back to your studio.');
   if(!await wait(3800))return;
   await go('room',true);if(token!==tourToken)return;
 }
 caption('Four places in one estate. Where would you like to go next?');
 if(!await wait(2500))return;stopTour();
}
$('#tourButton').onclick=startTour;$('#pageTourButton').onclick=startTour;
window.addEventListener('pagehide',persist);
renderDocument();setReduced(reduced);updateNavigation();wake();
// Progressive enhancement: use the same navigation action as the visible controls.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'navigate_scriptorium',title:'Navigate the Scriptorium',description:'Move between the room, seated desk and editable page in this local concept. Does not change document text.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['room','desk','page']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='view')||!['room','desk','page'].includes(input.view))throw new Error('Choose room, desk or page.');await go(input.view);return{view};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
