'use strict';
const rooms = {
  scriptorium: {name:'The Scriptorium', short:'Scriptorium', image:'room.png', aspect:1672/941, focus:[.5,.425], zoom:1.9, seat:true, station:'Your writing desk', action:'Open your manuscript', page:'Page', invitation:'Make yourself comfortable.', description:'A quiet place to give an idea its first words.', practice:'Write', previous:'marketplace', next:'laboratory', passage:'Through the glass passage', alt:'An inhabited writing room with teal structures, daylight and copper desks.'},
  laboratory: {name:'The Laboratory', short:'Laboratory', image:'laboratory.png', aspect:2172/724, focus:[.63,.62], zoom:.48, station:'Your research bench', action:'Open your research report', page:'Report', invitation:'Stay beside the experiment.', description:'Observe, compare, and write where the work happens.', practice:'Investigate', previous:'scriptorium', next:'makers', passage:'Along the light-filled gallery', alt:'First-person view at a research desk inside the laboratory, beside scientists and instruments.'},
  makers: {name:'The Makers’ Studio', short:'Makers’ studio', image:'makers.png', aspect:2171/724, focus:[.51,.62], zoom:.48, station:'Your creative bench', action:'Open your storyboard', page:'Edit', invitation:'See what the next frame could become.', description:'Images become sequences; a story finds its rhythm.', practice:'Make', previous:'laboratory', next:'marketplace', passage:'Down to the evening market', alt:'A digital creative studio with an editing bench, storyboards and a performance space.'},
  marketplace: {name:'The Marketplace', short:'Marketplace', image:'market.png', aspect:1672/941, focus:[.27,.65], zoom:.55, station:'The visual studies stall', action:'Browse the collection', page:'Browse', invitation:'Bring something interesting back with you.', description:'Discover work, linger over a study, take an idea home.', practice:'Discover', previous:'makers', next:'scriptorium', passage:'Back through the quiet wing', alt:'An evening market inside an invented estate, with art stalls, creative work and people gathering.'}
};
let roomId = 'scriptorium';
const currentRoom = () => rooms[roomId];
const researchDocs = [
 {id:'chapter-1',name:'Report',subtitle:'The changing signal',title:'When the Signal Changes',text:'This demonstration compares two synthetic response curves. The measured quantity is expressed in arbitrary units; these values are fictional and do not describe a real experiment.\n\nIn Run A, the response rises quickly before settling near a plateau. Run B rises more slowly and reaches a lower final value.\n\nThe curves give us a question to investigate, not a mechanism to declare. We would need repeat measurements, controls and uncertainty estimates before drawing a scientific conclusion.',suggestion:'A useful next step would be to repeat both conditions and compare the spread between independent runs.',disposition:'pending'},
 {id:'chapter-2',name:'Observations',subtitle:'What the traces show',title:'Beside the Instrument',text:'Run A: a steep early increase, followed by smaller changes.\n\nRun B: a slower rise across the same time window.\n\nQuestions to carry forward\nWas the baseline stable? Were conditions held constant? Does the apparent plateau survive a longer observation window?\n\nThese are fictional observations for the interactive concept.',suggestion:'Keep observations separate from interpretations, so a new result can change the explanation without erasing the record.',disposition:'pending'},
 {id:'scene-notes',name:'Next experiment',subtitle:'A plan to test',title:'What Would We Try Next?',text:'Repeat each condition independently.\n\nInclude a baseline control.\n\nRecord the conditions alongside each run.\n\nDecide on the comparison before inspecting the results.\n\nThis notebook is a fictional demonstration, not a laboratory protocol.',suggestion:'Write down what result would change your mind before starting the next run.',disposition:'pending'}
];
const studyCatalog = [
 {id:'threshold',title:'The threshold',image:'room.png',category:'Spaces',note:'A room waiting for its next inhabitant.'},
 {id:'light',title:'An answering light',image:'makers.png',category:'Making',note:'A gesture, a projection, and the moment between them.'},
 {id:'signal',title:'Beside the signal',image:'laboratory.png',category:'Spaces',note:'The writer of a report remains inside the experiment.'},
 {id:'evening',title:'After the day’s work',image:'market.png',category:'Gathering',note:'A place where finished work starts another conversation.'},
 {id:'room',title:'A place to begin',image:'scene-study.png',category:'Spaces',note:'Warm light and a little room for an unfinished idea.'}
];
